// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activity = { activity_id: number, car_id: number | null, contact_id: number, activity_type_id: number, tracker_id: number | null, started_at: string | null, finished_at: string | null, finished_latitude: number | null, finished_longitude: number | null, description: string | null, created_at: string, updated_at: string, deleted_at: string | null, };
