// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityMarker = { id: number, action: "POST" | "PUT" | "DELETE", name: string | null, latitude: number | null, longitude: number | null, };
