// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityExport = { activity_id: number, name: string, activity_count: bigint | null, created_at: string, updated_at: string, deleted_at: string | null, };
