// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Car = { car_id: number, name: string, police_number: string, active: boolean, car_type_id: number, tracker_id: number | null, created_at: string, updated_at: string, deleted_at: string | null, };
