// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarAudit = { audit_id: bigint, car_id: number | null, tracker_id: number, latitude: number, longitude: number, recorded_at: string, created_at: string, updated_at: string, deleted_at: string | null, };
