// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarBody = { name: string, police_number: string, active: boolean, car_type_id: number, tracker_id: number | null, };
