// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarStatusDetails = { car_status_id: number, car_id: number, car_name: string, car_police_number: string, gas_level: number, kilometres: number, recorded_at: string, created_at: string, updated_at: string, deleted_at: string | null, };
