// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarStatusBody = { car_id: number, gas_level: number, kilometres: number, status_type: "DEPARTURE" | "RETURN", };
