// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarTypeWithCount = { car_type_id: number, name: string, car_count: bigint, };
