// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CarWithTracker = { car_id: number, name: string, police_number: string, active: boolean, car_type_id: number, car_type_name: string, tracker_id: number | null, tracker_name: string | null, };
