// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactTypeWithCount = { contact_type_id: number, name: string, contact_count: bigint, };
