// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Distances = { activity_id: number, tracker_id: number, tracker_name: string, car_id: number, car_name: string, car_police_number: string, distance: number, };
