// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityTypeDetails } from "./ActivityTypeDetails";

export type GetActivityTypesResponse = { activity_types: Array<ActivityTypeDetails>, activity_type_count: number, };
