// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityDetails } from "./ActivityDetails";

export type GetActivitiesResponse = { activities: Array<ActivityDetails>, activity_count: number, };
