// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarAudit } from "./CarAudit";

export type GetAuditResponse = { total_count: number, audit_records: Array<CarAudit>, };
