// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityWithCount } from "./ActivityWithCount";

export type GetActivitiesResponse = { activities: Array<ActivityWithCount>, activity_count: number, };
