// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactDetails } from "./ContactDetails";

export type GetContactsResponse = { contacts: Array<ContactDetails>, contact_count: number, };
