// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarTypeWithCount } from "./CarTypeWithCount";

export type GetCarTypesResponse = { car_types: Array<CarTypeWithCount>, car_type_count: number, };
