// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarTypeDetails } from "./CarTypeDetails";

export type GetCarTypesResponse = { car_types: Array<CarTypeDetails>, car_type_count: number, };
