// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactWithDetails } from "./ContactWithDetails";

export type GetContactsResponse = { contacts: Array<ContactWithDetails>, contact_count: number, };
