// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarDetails } from "./CarDetails";

export type GetCarsResponse = { cars: Array<CarDetails>, car_count: number, };
