// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactTypeWithCount } from "./ContactTypeWithCount";

export type GetContactTypesResponse = { contact_types: Array<ContactTypeWithCount>, contact_type_count: number, };
