// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarStatusDetails } from "./CarStatusDetails";

export type GetCarStatusesResponse = { car_statuses: Array<CarStatusDetails>, car_status_count: number, };
