// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactTypeDetails } from "./ContactTypeDetails";

export type GetContactTypesResponse = { contact_types: Array<ContactTypeDetails>, contact_type_count: number, };
