// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryWithDetails } from "./HistoryWithDetails";

export type GetHistoriesResponse = { histories: Array<HistoryWithDetails>, history_count: number, };
