// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadAltitude } from "./PayloadAltitude";
import type { PayloadConnection } from "./PayloadConnection";
import type { PayloadCourse } from "./PayloadCourse";
import type { PayloadDateTime } from "./PayloadDateTime";
import type { PayloadHdop } from "./PayloadHdop";
import type { PayloadLocation } from "./PayloadLocation";
import type { PayloadSatellites } from "./PayloadSatellites";
import type { PayloadSpeed } from "./PayloadSpeed";
import type { PayloadStats } from "./PayloadStats";

export type GetMqttPayloadHistory = { id: number, uptime: number, connection: PayloadConnection, location: PayloadLocation, altitude: PayloadAltitude, speed: PayloadSpeed, course: PayloadCourse, datetime: PayloadDateTime, satellites: PayloadSatellites, hdop: PayloadHdop, stats: PayloadStats, };
