// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackerDetails } from "./TrackerDetails";

export type GetTrackerResponse = { trackers: Array<TrackerDetails>, tracker_count: number, };
