// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackerWithDetails } from "./TrackerWithDetails";

export type GetTrackerResponse = { trackers: Array<TrackerWithDetails>, tracker_count: number, };
