// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRoleDetails } from "./UserRoleDetails";

export type GetUserRolesResponse = { user_roles: Array<UserRoleDetails>, user_role_count: number, };
