// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRoleWithDetails } from "./UserRoleWithDetails";

export type GetUserRolesResponse = { user_roles: Array<UserRoleWithDetails>, user_role_count: number, };
