// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleMapLocationBias } from "./GoogleMapLocationBias";

export type GoogleMapPayload = { textQuery: string, languageCode: string, locationBias: GoogleMapLocationBias | null, pageSize: number | null, };
