// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Place } from "./Place";

export type GoogleMapResponse = { places: Array<Place>, };
