// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type History = { history_id: number, car_id: number | null, contact_id: number, activity_id: number, tracker_id: number | null, finished_at: string | null, started_at: string | null, finished_latitude: number, finished_longitude: number, description: string | null, };
