// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryExport = { "History ID": number, "Car ID": number | null, "Car Name": string | null, "Contact ID": number, "Contact Name": string, "Activity ID": number, "Activity Name": string, "Tracker ID": number | null, "Tracker Name": string | null, "Finished At": string | null, "Started At": string | null, "Finished Latitude": number, "Finished Longitude": number, Description: string | null, "Created At": string, "Updated At": string, "Deleted At": string | null, };
