// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryWithDetails = { history_id: number, car_id: number | null, car_name: string | null, contact_id: number, contact_name: string, activity_id: number, activity_name: string, tracker_id: number | null, tracker_name: string | null, finished_at: string | null, started_at: string | null, finished_latitude: number, finished_longitude: number, description: string | null, };
