// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadNetwork = { rssi: number | null, lac: string | null, ci: string | null, };
