// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadStats = { chars_processed: number | null, sentences_with_fix: number | null, failed_checksum: number | null, passed_checksum: number | null, };
