// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadSatellites = { visible: number | null, used: number | null, carrier_to_noise: number | null, age: number | null, valid: boolean, };
