// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadSpeed = { kmph: number | null, mph: number | null, mps: number | null, knots: number | null, age: number | null, valid: boolean, };
