// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PayloadConnection = { interval: number, retries: number, sequence_id: number, iteration_id: number, };
