// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceDisplayName } from "./PlaceDisplayName";
import type { PlaceLocation } from "./PlaceLocation";

export type Place = { id: string, formatted_address: string, location: PlaceLocation, display_name: PlaceDisplayName, };
