// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackerDetails = { tracker_id: number, name: string, car_id: number | null, car_name: string | null, car_police_number: string | null, car_type_id: number | null, car_type_name: string | null, created_at: string, updated_at: string, deleted_at: string | null, };
