// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackerAltitude } from "./TrackerAltitude";
import type { TrackerConnection } from "./TrackerConnection";
import type { TrackerCourse } from "./TrackerCourse";
import type { TrackerDateTime } from "./TrackerDateTime";
import type { TrackerHdop } from "./TrackerHdop";
import type { TrackerLocation } from "./TrackerLocation";
import type { TrackerSatellites } from "./TrackerSatellites";
import type { TrackerSpeed } from "./TrackerSpeed";
import type { TrackerStats } from "./TrackerStats";

export type TrackerPayloadWithId = { id: number, uptime: number, connection: TrackerConnection, location: TrackerLocation, altitude: TrackerAltitude, speed: TrackerSpeed, course: TrackerCourse, datetime: TrackerDateTime, satellites: TrackerSatellites, hdop: TrackerHdop, stats: TrackerStats, };
