// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackerDateTime = { iso8601: string | null, year: number | null, month: number | null, day: number | null, hour: number | null, minute: number | null, second: number | null, centisecond: number | null, valid: boolean, };
