// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackerAltitude = { meters: number | null, feet: number | null, age: number | null, valid: boolean, };
