// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateActivity = { activity_id: number, contact_name: string, contact_latitude: number, contact_longitude: number, };
