// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRoleWithDetails = { user_role_id: number, name: string, user_count: bigint, };
