// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserBody = { username: string, password: string | null, email: string, full_name: string, user_role_id: number, };
