// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAuth = { username: string, password: string, user_role_id: number, user_role_name: string, };
