// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsersExport = { user_id: number, username: string, email: string, full_name: string, user_role_id: number, user_role_name: string, created_at: string, updated_at: string, deleted_at: string | null, };
