// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserWithDetails = { user_id: number, username: string, email: string, full_name: string, user_role_id: number, user_role_name: string, };
