// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Format that's used for WebSocket messages
 * There will be three format, each representing different messages.
 *
 * No. 1, live Tracker location (real-time)
 * ```rust
 * {
 *     "message_type": "tracker_location",
 *     "data": MqttPayloadWithId
 * }
 * ```
 *
 * No. 2, new or update destination (when created or updated)
 * ```rust
 * {
 *     "message_type": "update_destination",
 *     "data": UpdateActivity
 * }
 * ```
 *
 * No. 3, delete destination (when deleted or finished)
 * ```rust
 * {
 *     "message_type": "remove_destination",
 *     "data": DeleteActivity
 * }
 * ```
 *
 * No. 4, closest tracker distances to destination
 * ```rust
 *     "message_type": "distances",
 *     "data": {
 *         "1": Distances,
 *         "2": Distances
 *     }
 * }
 * ```
 *
 * No. 5, tracker on the last 60 minute
 * ```rust
 * {
 *     "message_type": "audit",
 *     "data": {
 *         "1": Vec<Option<MqttPayloadWithId>>
 *         "2": Vec<Option<MqttPayloadWithId>>
 *     }
 * }
 */
export type WebSocketMessage = { message_type: string, data: JsonValue, };
