use sea_orm_migration::{prelude::*, schema::*};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(HardwareTest::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(HardwareTest::TestId)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(integer(HardwareTest::TrackerId))
                    .col(
                        ColumnDef::new(HardwareTest::Uptime)
                            .integer()
                            .unsigned()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::ConnectionInterval)
                            .integer()
                            .unsigned()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::ConnectionRetries)
                            .integer()
                            .unsigned()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::ConnectionSequenceId)
                            .integer()
                            .unsigned()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::ConnectionIterationId)
                            .integer()
                            .unsigned()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::NetworkRssi)
                            .integer()
                            .unsigned(),
                    )
                    .col(string_null(HardwareTest::NetworkLac))
                    .col(string_null(HardwareTest::NetworkCi))
                    .col(ColumnDef::new(HardwareTest::LocationLatitude).double())
                    .col(ColumnDef::new(HardwareTest::LocationLongitude).double())
                    .col(
                        ColumnDef::new(HardwareTest::LocationAge)
                            .integer()
                            .unsigned(),
                    )
                    .col(boolean(HardwareTest::LocationValid))
                    .col(ColumnDef::new(HardwareTest::AltitudeMeters).double())
                    .col(ColumnDef::new(HardwareTest::AltitudeFeet).double())
                    .col(
                        ColumnDef::new(HardwareTest::AltitudeAge)
                            .integer()
                            .unsigned(),
                    )
                    .col(boolean(HardwareTest::AltitudeValid))
                    .col(ColumnDef::new(HardwareTest::SpeedKmph).double())
                    .col(ColumnDef::new(HardwareTest::SpeedMph).double())
                    .col(ColumnDef::new(HardwareTest::SpeedMps).double())
                    .col(ColumnDef::new(HardwareTest::SpeedKnots).double())
                    .col(ColumnDef::new(HardwareTest::SpeedAge).integer().unsigned())
                    .col(boolean(HardwareTest::SpeedValid))
                    .col(ColumnDef::new(HardwareTest::CourseDegrees).double())
                    .col(ColumnDef::new(HardwareTest::CourseAge).integer().unsigned())
                    .col(boolean(HardwareTest::CourseValid))
                    .col(string_null(HardwareTest::DatetimeIso8601))
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeYear)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeMonth)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeDay)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeHour)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeMinute)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeSecond)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeCentisecond)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::DatetimeAge)
                            .integer()
                            .unsigned(),
                    )
                    .col(boolean(HardwareTest::DatetimeValid))
                    .col(
                        ColumnDef::new(HardwareTest::SatellitesVisible)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::SatellitesUsed)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::SatellitesCarrierToNoise)
                            .tiny_integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::SatellitesAge)
                            .integer()
                            .unsigned(),
                    )
                    .col(boolean(HardwareTest::SatellitesValid))
                    .col(ColumnDef::new(HardwareTest::DopHdop).double())
                    .col(ColumnDef::new(HardwareTest::DopPdop).double())
                    .col(ColumnDef::new(HardwareTest::DopVdop).double())
                    .col(ColumnDef::new(HardwareTest::DopAge).integer().unsigned())
                    .col(boolean(HardwareTest::DopValid))
                    .col(
                        ColumnDef::new(HardwareTest::StatsCharsProcessed)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::StatsSentencesWithFix)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::StatsFailedChecksum)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::StatsPassedChecksum)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::PayloadSize)
                            .integer()
                            .unsigned(),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::ReceivedAt)
                            .custom("DATETIME(3)")
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(HardwareTest::CreatedAt)
                            .custom("DATETIME(3)")
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(HardwareTest::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum HardwareTest {
    Table,
    TestId,
    TrackerId,
    Uptime,
    ConnectionInterval,
    ConnectionRetries,
    ConnectionSequenceId,
    ConnectionIterationId,
    NetworkRssi,
    NetworkLac,
    NetworkCi,
    LocationLatitude,
    LocationLongitude,
    LocationAge,
    LocationValid,
    AltitudeMeters,
    AltitudeFeet,
    AltitudeAge,
    AltitudeValid,
    SpeedKmph,
    SpeedMph,
    SpeedMps,
    SpeedKnots,
    SpeedAge,
    SpeedValid,
    CourseDegrees,
    CourseAge,
    CourseValid,
    DatetimeIso8601,
    DatetimeYear,
    DatetimeMonth,
    DatetimeDay,
    DatetimeHour,
    DatetimeMinute,
    DatetimeSecond,
    DatetimeCentisecond,
    DatetimeAge,
    DatetimeValid,
    SatellitesVisible,
    SatellitesUsed,
    SatellitesCarrierToNoise,
    SatellitesAge,
    SatellitesValid,
    DopHdop,
    DopPdop,
    DopVdop,
    DopAge,
    DopValid,
    StatsCharsProcessed,
    StatsSentencesWithFix,
    StatsFailedChecksum,
    StatsPassedChecksum,
    PayloadSize,
    ReceivedAt,
    CreatedAt,
}
