-- Add migration script here
CREATE TABLE hardware_test (
    test_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tracker_id INT NOT NULL,
    uptime INT UNSIGNED NOT NULL,
    connection_interval INT UNSIGNED NOT NULL,
    connection_retries INT UNSIGNED NOT NULL,
    connection_sequence_id INT UNSIGNED NOT NULL,
    connection_iteration_id INT UNSIGNED NOT NULL,
    network_rssi INT UNSIGNED NULL,
    network_lac VARCHAR(255) NULL,
    network_ci VARCHAR(255) NULL,
    location_latitude DOUBLE NULL,
    location_longitude DOUBLE NULL,
    location_age INT UNSIGNED NULL,
    location_valid BOOLEAN NOT NULL,
    altitude_meters DOUBLE NULL,
    altitude_feet DOUBLE NULL,
    altitude_age INT UNSIGNED NULL,
    altitude_valid BOOLEAN NOT NULL,
    speed_kmph DOUBLE NULL,
    speed_mph DOUBLE NULL,
    speed_mps DOUBLE NULL,
    speed_knots DOUBLE NULL,
    speed_age INT UNSIGNED NULL,
    speed_valid BOOLEAN NOT NULL,
    course_degrees DOUBLE NULL,
    course_age INT UNSIGNED NULL,
    course_valid BOOLEAN NOT NULL,
    datetime_iso8601 VARCHAR(255) NULL,
    datetime_year INT UNSIGNED NULL,
    datetime_month TINYINT UNSIGNED NULL,
    datetime_day TINYINT UNSIGNED NULL,
    datetime_hour TINYINT UNSIGNED NULL,
    datetime_minute TINYINT UNSIGNED NULL,
    datetime_second TINYINT UNSIGNED NULL,
    datetime_centisecond INT UNSIGNED NULL,
    datetime_age INT UNSIGNED NULL,
    datetime_valid BOOLEAN NOT NULL,
    satellites_visible TINYINT UNSIGNED NULL,
    satellites_used TINYINT UNSIGNED NULL,
    satellites_carrier_to_noise TINYINT UNSIGNED NULL,
    satellites_age INT UNSIGNED NULL,
    satellites_valid BOOLEAN NOT NULL,
    dop_hdop DOUBLE NULL,
    dop_pdop DOUBLE NULL,
    dop_vdop DOUBLE NULL,
    dop_age INT UNSIGNED NULL,
    dop_valid BOOLEAN NOT NULL,
    stats_chars_processed INT UNSIGNED NULL,
    stats_sentences_with_fix INT UNSIGNED NULL,
    stats_failed_checksum INT UNSIGNED NULL,
    stats_passed_checksum INT UNSIGNED NULL,
    received_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);