// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LoginError`, `LoginRequest`, `LoginSuccess`

Future<AuthResult> verify({required String token}) =>
    RustLib.instance.api.crateApiAuthVerify(token: token);

Future<AuthResult> login({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiAuthLogin(
  username: username,
  password: password,
);

class AuthResult {
  final bool success;
  final String? errorMessage;
  final String? token;

  const AuthResult({required this.success, this.errorMessage, this.token});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          token == other.token;
}
