// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CarResponse`

Future<CarResult> getCarById({required String token, required int carId}) =>
    RustLib.instance.api.crateApiCarGetCarById(token: token, carId: carId);

class Car {
  final int carId;
  final String name;
  final String policeNumber;
  final bool active;
  final int carTypeId;
  final String carTypeName;
  final int? trackerId;
  final String? trackerName;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;

  const Car({
    required this.carId,
    required this.name,
    required this.policeNumber,
    required this.active,
    required this.carTypeId,
    required this.carTypeName,
    this.trackerId,
    this.trackerName,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      carId.hashCode ^
      name.hashCode ^
      policeNumber.hashCode ^
      active.hashCode ^
      carTypeId.hashCode ^
      carTypeName.hashCode ^
      trackerId.hashCode ^
      trackerName.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Car &&
          runtimeType == other.runtimeType &&
          carId == other.carId &&
          name == other.name &&
          policeNumber == other.policeNumber &&
          active == other.active &&
          carTypeId == other.carTypeId &&
          carTypeName == other.carTypeName &&
          trackerId == other.trackerId &&
          trackerName == other.trackerName &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

class CarResult {
  final bool success;
  final String? errorMessage;
  final Car? car;

  const CarResult({required this.success, this.errorMessage, this.car});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode ^ car.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CarResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          car == other.car;
}
