// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<CarResult> getCarById({required String token, required int carId}) =>
    RustLib.instance.api.crateApiCarGetCarById(token: token, carId: carId);

class Car {
  final int carId;
  final String name;
  final String policeNumber;
  final int active;
  final String carType;
  final int? trackerId;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;

  const Car({
    required this.carId,
    required this.name,
    required this.policeNumber,
    required this.active,
    required this.carType,
    this.trackerId,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      carId.hashCode ^
      name.hashCode ^
      policeNumber.hashCode ^
      active.hashCode ^
      carType.hashCode ^
      trackerId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Car &&
          runtimeType == other.runtimeType &&
          carId == other.carId &&
          name == other.name &&
          policeNumber == other.policeNumber &&
          active == other.active &&
          carType == other.carType &&
          trackerId == other.trackerId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

class CarResult {
  final bool success;
  final String? errorMessage;
  final Car? car;

  const CarResult({required this.success, this.errorMessage, this.car});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode ^ car.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CarResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          car == other.car;
}
