// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CarStatusBody`, `HistoryResponse`

Future<HistoryResult> postHistory({
  required String token,
  required int carId,
  required double gasLevel,
  required double kilometres,
  required String statusType,
}) => RustLib.instance.api.crateApiHistoryPostHistory(
  token: token,
  carId: carId,
  gasLevel: gasLevel,
  kilometres: kilometres,
  statusType: statusType,
);

Future<HistoryResult> getHistories({required String token}) =>
    RustLib.instance.api.crateApiHistoryGetHistories(token: token);

class CarStatus {
  final int carStatusId;
  final int carId;
  final String carName;
  final String carPoliceNumber;
  final double gasLevel;
  final double kilometres;
  final String statusType;
  final String recordedAt;
  final String createdAt;
  final String updatedAt;
  final String? deletedAt;

  const CarStatus({
    required this.carStatusId,
    required this.carId,
    required this.carName,
    required this.carPoliceNumber,
    required this.gasLevel,
    required this.kilometres,
    required this.statusType,
    required this.recordedAt,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      carStatusId.hashCode ^
      carId.hashCode ^
      carName.hashCode ^
      carPoliceNumber.hashCode ^
      gasLevel.hashCode ^
      kilometres.hashCode ^
      statusType.hashCode ^
      recordedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CarStatus &&
          runtimeType == other.runtimeType &&
          carStatusId == other.carStatusId &&
          carId == other.carId &&
          carName == other.carName &&
          carPoliceNumber == other.carPoliceNumber &&
          gasLevel == other.gasLevel &&
          kilometres == other.kilometres &&
          statusType == other.statusType &&
          recordedAt == other.recordedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}

class HistoryResult {
  final bool success;
  final String? errorMessage;
  final List<CarStatus>? items;

  const HistoryResult({required this.success, this.errorMessage, this.items});

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          items == other.items;
}
