//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::StatusType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "car_status")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub car_status_id: i32,
    pub car_id: i32,
    #[sea_orm(column_type = "Double")]
    pub gas_level: f64,
    #[sea_orm(column_type = "Double")]
    pub kilometres: f64,
    pub status_type: StatusType,
    pub recorded_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cars::Entity",
        from = "Column::CarId",
        to = "super::cars::Column::CarId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Cars,
}

impl Related<super::cars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cars.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
