//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::CarType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cars")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub car_id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub police_number: String,
    pub active: i8,
    pub car_type: CarType,
    #[sea_orm(unique)]
    pub tracker_id: Option<i32>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activities::Entity")]
    Activities,
    #[sea_orm(has_many = "super::audit::Entity")]
    Audit,
    #[sea_orm(has_many = "super::car_status::Entity")]
    CarStatus,
    #[sea_orm(
        belongs_to = "super::trackers::Entity",
        from = "Column::TrackerId",
        to = "super::trackers::Column::TrackerId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Trackers,
}

impl Related<super::activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activities.def()
    }
}

impl Related<super::audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audit.def()
    }
}

impl Related<super::car_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CarStatus.def()
    }
}

impl Related<super::trackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trackers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
