//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hardware_test")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub test_id: i64,
    pub tracker_id: i32,
    pub uptime: u32,
    pub connection_interval: u32,
    pub connection_retries: u32,
    pub connection_sequence_id: u32,
    pub connection_iteration_id: u32,
    pub network_rssi: Option<u32>,
    pub network_lac: Option<String>,
    pub network_ci: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub location_latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub location_longitude: Option<f64>,
    pub location_age: Option<u32>,
    pub location_valid: i8,
    #[sea_orm(column_type = "Double", nullable)]
    pub altitude_meters: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub altitude_feet: Option<f64>,
    pub altitude_age: Option<u32>,
    pub altitude_valid: i8,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed_kmph: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed_mph: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed_mps: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub speed_knots: Option<f64>,
    pub speed_age: Option<u32>,
    pub speed_valid: i8,
    #[sea_orm(column_type = "Double", nullable)]
    pub course_degrees: Option<f64>,
    pub course_age: Option<u32>,
    pub course_valid: i8,
    pub datetime_iso8601: Option<String>,
    pub datetime_year: Option<u32>,
    pub datetime_month: Option<u32>,
    pub datetime_day: Option<u32>,
    pub datetime_hour: Option<u32>,
    pub datetime_minute: Option<u32>,
    pub datetime_second: Option<u32>,
    pub datetime_centisecond: Option<u32>,
    pub datetime_age: Option<u32>,
    pub datetime_valid: i8,
    pub satellites_visible: Option<u32>,
    pub satellites_used: Option<u32>,
    pub satellites_carrier_to_noise: Option<u32>,
    pub satellites_age: Option<u32>,
    pub satellites_valid: i8,
    #[sea_orm(column_type = "Double", nullable)]
    pub dop_hdop: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dop_pdop: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dop_vdop: Option<f64>,
    pub dop_age: Option<u32>,
    pub dop_valid: i8,
    pub stats_chars_processed: Option<u32>,
    pub stats_sentences_with_fix: Option<u32>,
    pub stats_failed_checksum: Option<u32>,
    pub stats_passed_checksum: Option<u32>,
    pub received_at: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
