//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::activities::Entity as Activities;
pub use super::audit::Entity as Audit;
pub use super::car_status::Entity as CarStatus;
pub use super::cars::Entity as Cars;
pub use super::contacts::Entity as Contacts;
pub use super::hardware_test::Entity as HardwareTest;
pub use super::trackers::Entity as Trackers;
pub use super::users::Entity as Users;
