//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ActivityType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "activities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub activity_id: i32,
    pub car_id: Option<i32>,
    pub contact_id: i32,
    pub activity_type: ActivityType,
    pub tracker_id: Option<i32>,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    #[sea_orm(column_type = "Double", nullable)]
    pub finished_latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub finished_longitude: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cars::Entity",
        from = "Column::CarId",
        to = "super::cars::Column::CarId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Cars,
    #[sea_orm(
        belongs_to = "super::contacts::Entity",
        from = "Column::ContactId",
        to = "super::contacts::Column::ContactId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contacts,
    #[sea_orm(
        belongs_to = "super::trackers::Entity",
        from = "Column::TrackerId",
        to = "super::trackers::Column::TrackerId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Trackers,
}

impl Related<super::cars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cars.def()
    }
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl Related<super::trackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trackers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
