//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "audit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub audit_id: i64,
    pub car_id: Option<i32>,
    pub tracker_id: i32,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    pub recorded_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cars::Entity",
        from = "Column::CarId",
        to = "super::cars::Column::CarId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Cars,
    #[sea_orm(
        belongs_to = "super::trackers::Entity",
        from = "Column::TrackerId",
        to = "super::trackers::Column::TrackerId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Trackers,
}

impl Related<super::cars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cars.def()
    }
}

impl Related<super::trackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trackers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
