//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "activity_type")]
pub enum ActivityType {
    #[sea_orm(string_value = "Delivery")]
    Delivery,
    #[sea_orm(string_value = "Meeting")]
    Meeting,
    #[sea_orm(string_value = "Trial T1")]
    TrialT1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "car_type")]
pub enum CarType {
    #[sea_orm(string_value = "Delivery")]
    Delivery,
    #[sea_orm(string_value = "Passenger")]
    Passenger,
}

impl CarType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Delivery => "delivery",
            Self::Passenger => "passenger",
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "contact_type")]
pub enum ContactType {
    #[sea_orm(string_value = "Consumer")]
    Consumer,
    #[sea_orm(string_value = "Supplier")]
    Supplier,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "status_type")]
pub enum StatusType {
    #[sea_orm(string_value = "Departure")]
    Departure,
    #[sea_orm(string_value = "Return")]
    Return,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Security")]
    Security,
    #[sea_orm(string_value = "Employee")]
    Employee,
}
